declare class StatBonuses
{
    constructor();
    GetAC() : number;
    GetHP() : number;
    GetHPRegen() : number;
    GetMaxHP() : number;
    GetManaRegen() : number;
    GetEnduranceRegen() : number;
    GetMana() : number;
    GetEndurance() : number;
    GetATK() : number;
    GetSTR() : number;
    GetSTRCapMod() : number;
    GetHeroicSTR() : number;
    GetSTA() : number;
    GetSTACapMod() : number;
    GetHeroicSTA() : number;
    GetDEX() : number;
    GetDEXCapMod() : number;
    GetHeroicDEX() : number;
    GetAGI() : number;
    GetAGICapMod() : number;
    GetHeroicAGI() : number;
    GetINT() : number;
    GetINTCapMod() : number;
    GetHeroicINT() : number;
    GetWIS() : number;
    GetWISCapMod() : number;
    GetHeroicWIS() : number;
    GetCHA() : number;
    GetCHACapMod() : number;
    GetHeroicCHA() : number;
    GetMR() : number;
    GetMRCapMod() : number;
    GetHeroicMR() : number;
    GetFR() : number;
    GetFRCapMod() : number;
    GetHeroicFR() : number;
    GetCR() : number;
    GetCRCapMod() : number;
    GetHeroicCR() : number;
    GetPR() : number;
    GetPRCapMod() : number;
    GetHeroicPR() : number;
    GetDR() : number;
    GetDRCapMod() : number;
    GetHeroicDR() : number;
    GetCorrup() : number;
    GetCorrupCapMod() : number;
    GetHeroicCorrup() : number;
    GetDamageShieldSpellID() : number;
    GetDamageShield() : number;
    GetDamageShieldType() : number;
    GetSpellDamageShield() : number;
    GetSpellShield() : number;
    GetReverseDamageShield() : number;
    GetReverseDamageShieldSpellID() : number;
    GetReverseDamageShieldType() : number;
    Getmovementspeed() : number;
    Gethaste() : number;
    Gethastetype2() : number;
    Gethastetype3() : number;
    Getinhibitmelee() : number;
    GetAggroRange() : number;
    GetAssistRange() : number;
    Getskillmod(idx : number) : number;
    Getskillmodmax(idx : number) : number;
    Geteffective_casting_level() : number;
    Getadjusted_casting_skill() : number;
    Getreflect_chance() : number;
    GetsingingMod() : number;
    GetAmplification() : number;
    GetbrassMod() : number;
    GetpercussionMod() : number;
    GetwindMod() : number;
    GetstringedMod() : number;
    GetsongModCap() : number;
    Gethatemod() : number;
    GetEnduranceReduction() : number;
    GetStrikeThrough() : number;
    GetMeleeMitigation() : number;
    GetMeleeMitigationEffect() : number;
    GetCriticalHitChance(idx : number) : number;
    GetCriticalSpellChance() : number;
    GetSpellCritDmgIncrease() : number;
    GetSpellCritDmgIncNoStack() : number;
    GetDotCritDmgIncrease() : number;
    GetCriticalHealChance() : number;
    GetCriticalHealOverTime() : number;
    GetCriticalDoTChance() : number;
    GetCrippBlowChance() : number;
    GetAvoidMeleeChance() : number;
    GetAvoidMeleeChanceEffect() : number;
    GetRiposteChance() : number;
    GetDodgeChance() : number;
    GetParryChance() : number;
    GetDualWieldChance() : number;
    GetDoubleAttackChance() : number;
    GetTripleAttackChance() : number;
    GetDoubleRangedAttack() : number;
    GetResistSpellChance() : number;
    GetResistFearChance() : number;
    GetFearless() : boolean;
    GetIsFeared() : boolean;
    GetIsBlind() : boolean;
    GetStunResist() : number;
    GetMeleeSkillCheck() : number;
    GetMeleeSkillCheckSkill() : number;
    GetHitChance() : number;
    GetHitChanceEffect(idx : number) : number;
    GetDamageModifier(idx : number) : number;
    GetDamageModifier2(idx : number) : number;
    GetMinDamageModifier(idx : number) : number;
    GetProcChance() : number;
    GetProcChanceSPA() : number;
    GetExtraAttackChance() : number;
    GetDoTShielding() : number;
    GetFlurryChance() : number;
    GetHundredHands() : number;
    GetMeleeLifetap() : number;
    GetVampirism() : number;
    GetHealRate() : number;
    GetMaxHPChange() : number;
    GetHealAmt() : number;
    GetSpellDmg() : number;
    GetClairvoyance() : number;
    GetDSMitigation() : number;
    GetDSMitigationOffHand() : number;
    GetTwoHandBluntBlock() : number;
    GetItemManaRegenCap() : number;
    GetGravityEffect() : number;
    GetAntiGate() : boolean;
    GetMagicWeapon() : boolean;
    GetIncreaseBlockChance() : number;
    GetPersistantCasting() : number;
    GetXPRateMod() : number;
    GetBlockNextSpell() : boolean;
    GetImmuneToFlee() : boolean;
    GetVoiceGraft() : number;
    GetSpellProcChance() : number;
    GetCharmBreakChance() : number;
    GetSongRange() : number;
    GetHPToManaConvert() : number;
    GetNegateEffects() : boolean;
    GetTriggerMeleeThreshold() : boolean;
    GetTriggerSpellThreshold() : boolean;
    GetShieldBlock() : number;
    GetBlockBehind() : number;
    GetCriticalRegenDecay() : boolean;
    GetCriticalHealDecay() : boolean;
    GetCriticalDotDecay() : boolean;
    GetDivineAura() : boolean;
    GetDistanceRemoval() : boolean;
    GetFrenziedDevastation() : number;
    GetNegateIfCombat() : boolean;
    GetScreech() : number;
    GetAlterNPCLevel() : number;
    GetBerserkSPA() : boolean;
    GetMetabolism() : number;
    GetSanctuary() : boolean;
    GetFactionModPct() : number;
    GetPC_Pet_Flurry() : number;
    GetPackrat() : number;
    GetBuffSlotIncrease() : number;
    GetDelayDeath() : number;
    GetBaseMovementSpeed() : number;
    GetIncreaseRunSpeedCap() : number;
    GetDoubleSpecialAttack() : number;
    GetFrontalStunResist() : number;
    GetBindWound() : number;
    GetMaxBindWound() : number;
    GetChannelChanceSpells() : number;
    GetChannelChanceItems() : number;
    GetSeeInvis() : number;
    GetTripleBackstab() : number;
    GetFrontalBackstabMinDmg() : boolean;
    GetFrontalBackstabChance() : number;
    GetConsumeProjectile() : number;
    GetForageAdditionalItems() : number;
    GetSalvageChance() : number;
    GetArcheryDamageModifier() : number;
    GetSecondaryDmgInc() : boolean;
    GetGiveDoubleAttack() : number;
    GetPetCriticalHit() : number;
    GetPetAvoidance() : number;
    GetCombatStability() : number;
    GetDoubleRiposte() : number;
    GetAmbidexterity() : number;
    GetPetMaxHP() : number;
    GetPetFlurry() : number;
    GetMasteryofPast() : number;
    GetGivePetGroupTarget() : boolean;
    GetRootBreakChance() : number;
    GetUnfailingDivinity() : number;
    GetItemHPRegenCap() : number;
    GetOffhandRiposteFail() : number;
    GetItemATKCap() : number;
    GetShieldEquipDmgMod() : number;
    GetTriggerOnValueAmount() : boolean;
    GetStunBashChance() : number;
    GetIncreaseChanceMemwipe() : number;
    GetCriticalMend() : number;
    GetImprovedReclaimEnergy() : number;
    GetPetMeleeMitigation() : number;
    GetIllusionPersistence() : boolean;
    Getextra_xtargets() : number;
    GetShroudofStealth() : boolean;
    GetReduceFallDamage() : number;
    GetTradeSkillMastery() : number;
    GetNoBreakAESneak() : number;
    GetFeignedCastOnChance() : number;
    GetDivineSaveChance(idx : number) : number;
    GetDeathSave(idx : number) : number;
    GetAccuracy(idx : number) : number;
    GetSkillDmgTaken(idx : number) : number;
    GetSpellTriggers(idx : number) : number;
    GetSpellOnKill(idx : number) : number;
    GetSpellOnDeath(idx : number) : number;
    GetCritDmgMod(idx : number) : number;
    GetSkillReuseTime(idx : number) : number;
    GetSkillDamageAmount(idx : number) : number;
    GetHPPercCap(idx : number) : number;
    GetManaPercCap(idx : number) : number;
    GetEndPercCap(idx : number) : number;
    GetFocusEffects(idx : number) : number;
    GetFocusEffectsWorn(idx : number) : number;
    GetSkillDamageAmount2(idx : number) : number;
    GetNegateAttacks(idx : number) : number;
    GetMitigateMeleeRune(idx : number) : number;
    GetMeleeThresholdGuard(idx : number) : number;
    GetSpellThresholdGuard(idx : number) : number;
    GetMitigateSpellRune(idx : number) : number;
    GetMitigateDotRune(idx : number) : number;
    GetManaAbsorbPercentDamage(idx : number) : number;
    GetImprovedTaunt(idx : number) : number;
    GetRoot(idx : number) : number;
    GetAbsorbMagicAtt(idx : number) : number;
    GetMeleeRune(idx : number) : number;
    GetAStacker(idx : number) : number;
    GetBStacker(idx : number) : number;
    GetCStacker(idx : number) : number;
    GetDStacker(idx : number) : number;
    GetLimitToSkill(idx : number) : boolean;
    GetSkillProc(idx : number) : number;
    GetSkillProcSuccess(idx : number) : number;
    GetPC_Pet_Rampage(idx : number) : number;
    GetSkillAttackProc(idx : number) : number;
    GetSlayUndead(idx : number) : number;
    GetGiveDoubleRiposte(idx : number) : number;
    GetRaiseSkillCap(idx : number) : number;
    GetSEResist(idx : number) : number;
    GetFinishingBlow(idx : number) : number;
    GetFinishingBlowLvl(idx : number) : number;
    GetHeadShot(idx : number) : number;
    GetHSLevel(idx : number) : number;
    GetAssassinate(idx : number) : number;
    GetAssassinateLevel(idx : number) : number;
    GetReduceTradeskillFail(idx : number) : number;
}
